In [1]:
def greet(name):
    print(f"Hello, {name}")

In [2]:
greet("Alice")

Hello, Alice


In [3]:
employee = "Salim"
greet(employee)

Hello, Salim


In [4]:
def greet(name):
    name = name.upper()
    print(f"Hello, {name}")

greet("Alice")

Hello, ALICE


# Libraries

In [5]:
!pip install numpy

In [8]:
import numpy as np

In [9]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'arr

In [12]:
np.arange(start = 100, stop = 200, step = 33)

array([100, 133, 166, 199])

In [16]:
from numpy import arange #import only a specific function from the library
arange(start = 50, stop = 200, step = 33)

array([ 50,  83, 116, 149, 182])

In [17]:
# REQUESTS library
!pip install requests

In [19]:
import requests
url = "https://data.wa.gov/api/views/8pxm-d86c/rows.csv?accessType=DOWNLOAD"
requests.get(url)

<Response [200]>

In [20]:
response = requests.get(url)
response.text

'Year,District Name,School Name,cohort,Group,Group Value,Num Domains Ready,Pct\n2015-16,Aberdeen School District,A J West Elementary,ECEAP Cohort,All Students,All Students,3 or less,0.17\n2015-16,Aberdeen School District,A J West Elementary,ECEAP Cohort,All Students,All Students,4 or 5,0.24\n2015-16,Aberdeen School District,A J West Elementary,ECEAP Cohort,All Students,All Students,6 of 6,0.59\n2015-16,Aberdeen School District,A J West Elementary,ECEAP Cohort,Race/Ethnicity,Hispanic/Latino of any race(s),3 or less,0.4\n2015-16,Aberdeen School District,A J West Elementary,ECEAP Cohort,Race/Ethnicity,Hispanic/Latino of any race(s),4 or 5,0.1\n2015-16,Aberdeen School District,A J West Elementary,ECEAP Cohort,Race/Ethnicity,Hispanic/Latino of any race(s),6 of 6,0.5\n2015-16,Aberdeen School District,A J West Elementary,ECEAP Cohort,Race/Ethnicity,White,3 or less,0.06\n2015-16,Aberdeen School District,A J West Elementary,ECEAP Cohort,Race/Ethnicity,White,4 or 5,0.33\n2015-16,Aberdeen School 

# OS library


In [21]:
import os
os.getcwd() #get current working directory

'C:\\Users\\angel\\source\\Repo-1\\Day 3'

# CSV Library


In [24]:
import csv

with open("my_data.csv") as f:
    reader = csv.reader(f)    # iterator
    for row in reader:
        print(row)

['id', 'name', 'age', 'city']
['1', 'Alice', '34', 'New York']
['2', 'Bob', '23', 'Los Angeles']
['3', 'Charlie', '40', 'Chicago']
['4', 'Diana', '28', 'Houston']
['5', 'Evan', '19', 'Pheonix']


In [26]:
import csv

with open("my_data.csv") as f:
    reader = csv.DictReader(f)  # it creates a dictionary with key-value pairs
    for row in reader:
        print(row)

{'id': '1', 'name': 'Alice', 'age': '34', 'city': 'New York'}
{'id': '2', 'name': 'Bob', 'age': '23', 'city': 'Los Angeles'}
{'id': '3', 'name': 'Charlie', 'age': '40', 'city': 'Chicago'}
{'id': '4', 'name': 'Diana', 'age': '28', 'city': 'Houston'}
{'id': '5', 'name': 'Evan', 'age': '19', 'city': 'Pheonix'}


In [30]:
with open("my_data.csv") as f:
    reader = csv.DictReader(f)
    for row in reader:
        print(row["id"], row["city"]) #to see only some columns

1 New York
2 Los Angeles
3 Chicago
4 Houston
5 Pheonix


# Tkinter

In [31]:
import tkinter as tk

In [35]:
root = tk.Tk()

In [36]:
root.title("My first Tkinter window") # define title for the window (not mandatory)

''

In [37]:
""" 
We create widgets. root.mainloop() should be run at the end.
"""
welcome_label = tk.Label(root, text = "Welcome to Tkinter!") #create a label and associate it with the root, then to an object

In [38]:
welcome_label.pack() # it packages the label into the application we are building

In [39]:
def on_button_click():
    welcome_label.config(text="Button clicked")

In [40]:
click_me_button = tk.Button(root, text="Click me!", command = on_button_click)

In [41]:
# we have to pack the button as we did for the label
click_me_button.pack()

In [42]:
root.mainloop() # after running it, it opens a new window and we can't use jupyter until we close Tkinter

# Numpy

In [3]:
import numpy as np

In [5]:
"""
Let's create an array and once created it has to be associated to a variable (my_array). 
"""
my_array = np.array([1,10,-5,20])
my_array

array([ 1, 10, -5, 20])

In [8]:
print(f"The mean is {my_array.mean()}")
print(f"The mean is {my_array.std()}")

The mean is 6.5
The mean is 9.447221813845593


In [9]:
print(f"Multiplication by 2: {my_array*2}")

Multiplication by 2: [  2  20 -10  40]


In [10]:
"""
Multidimensional arrays (multiple lines -> width and height). Remember that since it's a single array, it needs an additional square brackets.
"""
my_arr_4x3 = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
my_arr_4x3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [11]:
my_arr_4x3*4

array([[ 4,  8, 12],
       [16, 20, 24],
       [28, 32, 36],
       [40, 44, 48]])

In [13]:
print(f"Inverted matrix:\n{my_arr_4x3.T}")

Inverted matrix:
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [14]:
# to knwo how many elements there are in the matrix
print(f"Elements in this matrix: {my_arr_4x3.size}")

Elements in this matrix: 12


In [15]:
print(f"Shape of this matrix: {my_arr_4x3.shape}") # 4 rows and 3 columns

Shape of this matrix: (4, 3)


In [19]:
random_integers = np.random.randint(100,200,20) 
random_integers

array([177, 121, 147, 167, 150, 194, 170, 172, 164, 165, 123, 125, 187,
       172, 145, 156, 154, 134, 113, 178], dtype=int32)

In [20]:
random_integers % 2

array([1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0],
      dtype=int32)

In [24]:
even_numbers = random_integers[random_integers % 2 == 0] # filter the whole array
even_numbers

array([150, 194, 170, 172, 164, 172, 156, 154, 134, 178], dtype=int32)

In [25]:
# then filter by position
sliced_array = even_numbers[2:8]
sliced_array

array([170, 172, 164, 172, 156, 154], dtype=int32)

In [27]:
arr1 = np.random.randint(0,10,4)
arr2 = np.random.randint(0,10,4)
print(f"The two arrays are:\n{arr1}\n{arr2}")

The two arrays are:
[4 9 4 1]
[8 3 5 5]


In [32]:
print(f"Sum of the two arrays is {arr1+arr2}")
print(f"Difference of the two arrays is {arr1-arr2}")
print(f"Multiplication of the two arrays is {arr1*arr2}")

Sum of the two arrays is [12 12  9  6]
Difference of the two arrays is [-4  6 -1 -4]
Multiplication of the two arrays is [32 27 20  5]


In [35]:
print(np.dot(arr1, arr2)) # it's the sum of the product of the arrays
print((arr1*arr2).sum())

84
84
